### ISSUE TITLE
fee=yes/no not selectiable via preset dialog

### ISSUE THREAD

**Issue by scaidermern** [simonpoole/beautified-JOSM-preset#139]
Unsure if this belongs here or to https://github.com/MarcusWolschon/osmeditor4android/issues

For the fee tag (e.g. for amenity=parking) vespucci shows a dialog where you can choose between opening hours and text values. However the radio button for text is not selectable. This makes it impossible to enter values `yes` and `no` except via the details widget.

**Comment by simonpoole** [comment]
That sounds like at least an issue in Vespucci, because on my devices and emulators switching back and forward "just works". Can you give full details (best via the feedback menu item in the main menu so you don't need to type your device information in), including any prior contents of the fee field?

**Comment by scaidermern** [comment]
I just did, see https://github.com/MarcusWolschon/osmeditor4android/issues/872.
