### ISSUE TITLE
Tag for ladder

### ISSUE THREAD

**Issue by simonpoole** [simonpoole/beautified-JOSM-preset#155]
Description:
---

There doesn't seem to be a tag and presets for ladders.

Device info:
---
<table>
<tr><td>App version</td><td>13.1.0.0</td></tr>
<tr><td>App version code</td><td>1203</td></tr>
<tr><td>Android build version</td><td>N950FXXU6DSD5</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PPR1.180610.011.N950FXXU6DSD5</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>greatlte</td></tr>
<tr><td>Device model</td><td>SM-N950F</td></tr>
<tr><td>Device product name</td><td>greatltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos8895</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by Lee-Carre** [comment]
> There doesn't seem to be a tag [or] presets for ladders.

While no preset (from experience of trying to map some, recently), there does seem to be at least a key: [ladder=*](http://wiki.openstreetmap.org/wiki/Key:ladder).

However, it seems intended for the likes of (mountainous) hiking trails, rather than a distinct feature. The context in which I was trying to add ladders was certainly not along a hiking trail(, but from a pier down into a harbour / marina).

Yet, TagInfo shows that it's [used fairly often](http://taginfo.openstreetmap.org/keys/ladder); ~2000 times.

Interestingly (if only for contrast & comparison) TagInfo lists a few [scuba_diving:entry:ladder](http://taginfo.openstreetmap.org/keys/scuba_diving:entry:ladder)s.

A preset for ladder(s) would be helpful; I'm on an island with many harbours / marinas, which often feature many ladders. There's also a few non-marine ladders dotted about, too.

For tagging, I would've thought highway=ladder (since there's highway=steps).
