### ISSUE TITLE
Consider supporting amenity=hospital without healthcare tag

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#177]
Currently `amenity=hospital` has no icon in Vespucci. Is it intentional to treat not tagging `healthcare=hospital` as a major tagging mistake?

**Comment by simonpoole** [comment]
It is completely on purpose and is the same behaviour as iD. The issue that you are referring too is actually that the top-level tags don't match individually in Vespucci because up to 14.1 all fixed tags in a preset had to match for it to even be a candidate for further matching. This has now been addressed with an additional preset attribute for 14.1.

See https://github.com/simonpoole/beautified-JOSM-preset/commit/8f97f0bcf526acd0a620dada80e9e8be816c43c6 and https://github.com/MarcusWolschon/osmeditor4android/commit/264f6a33857ba40c9f75d159637cd2853f1ac99d
