### ISSUE TITLE
 telephone poles

### ISSUE THREAD

**Issue by jidanni** [simonpoole/beautified-JOSM-preset#180]
I was unable to properly enter a telephone pole, because there is no preset ready for it. (Vespucci.)

**Comment by simonpoole** [comment]
Given that vespucci allows both direct tag entry and custom preset correction the "unable" is naturally wrong.

In any case there currently doesn't seem to be consensus on how to tag telephone poles (not to I believe that there has been any conclusive discussion on the tagging list), so it would seem to be premature to add a preset.

**Comment by jidanni** [comment]
OK, I'll try to remember
man_made=utility_pole
utility=telecom

**Comment by simonpoole** [comment]
No that's silly. YOu should write a wiki page and point to that.

**Comment by jidanni** [comment]
https://github.com/openstreetmap/iD/issues/6848

**Comment by simonpoole** [comment]
I've added utility_pole as a preset for now however it has the deprecated flag set so it won't be actively offered.

**Comment by davidpnewton** [comment]
So now, 8 months on there is still no way to display telephone poles properly in the software. Deprecated as a term implies that support was there but was subsequently removed. This has never been enabled at all, so having it in but deprecated is pointless. Please either remove it from the preset or enable it so that things display properly.

**Comment by davidpnewton** [comment]
This is now more relevant. A proposal for man_made=utility_pole has now actually been approved, and thus having the preset deprecated in Vespucci now makes no sense at all. Since it's an officially-approved tag please remove the deprecated flag from the preset.
