### ISSUE TITLE
Some icons are linked to svg files instead of png in the Vespucci version

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#263]
In the Vespucci preset xml some icons are still linked to svg files (a leftover from the JOSM version?), and so they are not displayed in Vespucci at all. It's not very much. Here are some examples:

- <item name="Transformer Tower" = styles/standard/power/transformer_tower.svg
- <item name="Terminal" => presets/power/terminal.svg
- <item name="Social Networks" => presets/misc/social_networks.svg
- ...

And also icons in some lists like crossing types in `<chunk id="crossing_type">` are affected.

I started to convert some svg files to png. Here are the results – it's not complete, but perhaps you can use them:

![crossing_unmarked_for_list](https://user-images.githubusercontent.com/48966999/116895873-ea59df00-ac33-11eb-9136-5f326d9dda5b.png)
![crossing_island_for_list](https://user-images.githubusercontent.com/48966999/116895876-eaf27580-ac33-11eb-9111-91702815526d.png)
![crossing_for_list](https://user-images.githubusercontent.com/48966999/116895878-eaf27580-ac33-11eb-94cd-633af4bc6967.png)
![crossing_traffic_signals_for_list](https://user-images.githubusercontent.com/48966999/116895879-eb8b0c00-ac33-11eb-8025-9ae115af7580.png)
![osm_contact_social_networks](https://user-images.githubusercontent.com/48966999/116895917-f5147400-ac33-11eb-80b0-34066d20d381.png)

**Comment by simonpoole** [comment]
See also https://github.com/simonpoole/beautified-JOSM-preset/issues/4

There are two issues here; 

- 1st and most important, the  license of the icon needs to be a file based license so not GPL,, best CC0, but CC BY is acceptable too, but then credits need to be added,
- 2nd you don't need to convert icons manually, most SVG icons should be merged/changed in to the SIJB template format and added to an appropriate sub-directory, coloring, conversion etc. is then taken care of during the build process.
- exceptions to the above are mostly traffic signs.

Note since a couple of releases we now have an additional level of indirection so that we can include links to the original JOSM icons in corresponding builds, see the beautified_icons.txt and josm_icons.txt files.

**Comment by simonpoole** [comment]
https://github.com/simonpoole/beautified-JOSM-preset/issues/286 duplicated this.
