### ISSUE TITLE
Notification about parking:condition proposal

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#296]
https://wiki.openstreetmap.org/wiki/Proposed_features/Parking_lane_conditionals is a new proposal that proposes changes to tags used by Vespucci presets.

I opened this issue to let you know about this (not sure are you interested, I have seen no earlier issues like this here, let me know if it was unwanted or some other notification method would be better).

If this proposal is flawed it would be likely a good idea to let know its proposer as soon as possible.

**Comment by jajajaneeneenee** [comment]
I saw that you implemented the changes caused by the proposal for the `parking:lane` and `parking:condition` keys in v3.6.0. Very nice! And a good idea to create 3 preset_link items ... The number of properties in roads can be really plentiful and difficult to keep track of when editing ... (By the way, some new layout/GUI features in the property editor of Vespucci like space dividers or any kind of visual grouping of tags would be very welcome. If this is possible in any way ...)

But some things are still missing, I guess. Perhaps to complete it, you could add something ...

**I think this would be important and quite useful (according to the new approved proposal and Wiki page):**

- Add value “no” to the values of `parking:lane:<side>`
- Add value “yes” to the values of` parking:lane:<side>`
- Add value “separate” to the values of `parking:lane:<side>`
- Add value “no_standing” to the values of `parking:lane:<side>` (with `deprecated="true"`)
- Add value “disabled” to the values of `parking:condition:<side>`

And another suggestion:
I would add the text "(deprecated)" behind the short_description text of `no_parking`, `no_stopping`, `fire_lane` (and `no_standing` if you add it), e.g. `short_description="No parking (deprecated)"`, as a textual information for users of the preset in JOSM (and in Vespucci where it is only displayed if editing an existing way with such an old key/value). This is very good as a hint when editing (especially for users who are not very familiar with the changes, but I would find it helpful, too).


**And optionally you could add this:**

Add 3 combo tags for the possible parking position tags (perhaps as optional keys):

- `parking:lane:<side>:parallel`
- `parking:lane:<side>:diagonal`
- `parking:lane:<side>:perpendicular`
(Each with the values `on_street`, `half_on_kerb`, `on_kerb`, `street_side`, `painted_area_only`, `shoulder` and perhaps `lay_by` as a deprecated value)

Add perhaps also add these 2 (optional) tags:

- `parking:condition:<side>:residents` (for a resident parking code, like “L1” which is written on the parking traffic signs. I need it quite often …)
- `parking:condition:<side>:reason` (a new optional tag, see proposal)


And perhaps you could also add the old (deprecated) tags at the end, at least for the Vespucci preset (not sure if JOSM supports the deprecated attribute) – with a textual addition to the text description of the key, that it is deprecated like mentioned above:

- `parking:condition:<side>:default` 
- `parking:condition:<side>:time_interval`

(Otherwise they will be shown as additional properties without any information for the users in Vespucci. And also in JOSM it could be helpful to see the old keys together with the new ones in the pop up window of the Lane Parking preset link items ... for example if you want to change to old to the new tagging scheme. Otherwise you have to search for them in the list of **all** keys/values and they are easily overlooked ...)
