### ISSUE TITLE
Power line tagging issue

### ISSUE THREAD

**Issue by davidpnewton** [simonpoole/beautified-JOSM-preset#307]
There appears to be a bug with the tagging of power lines.

When an item such as way 1017240731 is edited the software appears to always automatically add the tagging line=busbar to the way, altering the matched preset from Power line to Power busbar. As you will see from the aerial imagery that way is definitely not a busbar!

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/fb855855ad04a1e01ace0212f819ba9322228888

This is things conspiring so that the scoring is only matching on attribute tags instead of on the "fixed" tags for the object (essentially that means that any power=line line=something object was matching). I would recommend manually installing the current preset manually. I'll be changing the matching algo slightly so that this shouldn't be so easy to do in the future.
