### ISSUE TITLE
Advanced stop line preset bug

### ISSUE THREAD

**Issue by davidpnewton** [simonpoole/beautified-JOSM-preset#310]
The advanced stop line preset whuch adds cycleway=asl to a node appears to have a bug associated with it. Using it adds the tagging to the node but the icon for the preset does not show up in the map editing view nor is the preset detected as present when the node is later edited with Unknown element (no preset found) displayed instead.

**Comment by simonpoole** [comment]
The reason for this is that it is that it is really bad tagging, but it makes sense to allow it till the time that the information can be used in something that actually works.

The underlying problem is that somehow we need to differentiate between tags that actually define objects and such that don't , i.e. the difference between amenity=parking and colour=blue. 

In the case of cycleway=asl cycleway is a key that previously had only been used on highway objects, so for example highway=primary cycleway=... of as a subtype of highway=cycleway. Now suddenly it is being used as its own top level object. 

We have a mechanism to support  configuration of this, but the more top level keys are allowed the more difficult it becomes to do reasonable matching so I've been reluctant to add cycleway to the list. There is an open issue to expand the facility to include  full tags which would make adding tags like this slight less obnoxious, but that hasn't been implemented yet, see  https://github.com/MarcusWolschon/osmeditor4android/issues/892
