### ISSUE TITLE
Searching for shed only finds building part

### ISSUE THREAD

**Issue by jidanni** [simonpoole/beautified-JOSM-preset#366]
https://wiki.openstreetmap.org/wiki/Tag:building%3Dshed should appear when we search for shed.

**Comment by simonpoole** [comment]
We don't maintain synonyms here (not the least because the JOSM format doesn't support them). 

If you are looking for the source of synonyms Vespucci uses, we use those added via translations to https://github.com/openstreetmap/id-tagging-schema

**Comment by tyrasd** [comment]
@simonpoole I don't understand why you linked the id-tagging-schema repository here? It does already have a preset for `building=shed` with the name "Shed", but still Vespucci does not find it when searching for it.

What would you propose to be done to fix this issue?

**Comment by simonpoole** [comment]
@tyrasd jidanni confusingly opened two issues. The actual issue was that he was searching for "workshop" and didn't get "shed" or rather the general building preset as one of the results (searching for "shed" does return the building preset). That is technically down to the synonyms / terms not containing "workshop" (which I see you've added in the meantime).

Now if it is even reasonable to expect every thing mentioned in the wiki to somehow magically turn up in the synonyms is a different question. I would respectfully suggest that if a user wants that, they should set aside a day or two per week to work on it.
