### ISSUE TITLE
Various augmentation requests.

### ISSUE THREAD

**Issue by sekerob** [simonpoole/beautified-JOSM-preset#404]
Loaded up BP in JOSM and removed Internal presets after a little 5 icons disappeared from the toolbar, 3 I found back by just pinning the BP versions, 1 icon completely went AWOL, found no replacement. Traffic sign icons still an issue although now they seem to be in PNG where before they would not show when in SVG format, no matter what, I get the text on the toolbar, no icon.

1) Surprised not to find a 'denotation' tag on the BP version of the tree row preset (agricultural, decoration, street, urban, avenue...). Filed a request at JOSM a year ago for the addition, a reason I switched to custom presets.
2) The noexit preset is iconless as well and shows up as text on the toolbar 'Annotation/No Exit', but if a node is tagged you get a no exit traffic sign icon so it must exist in the system.  Mapped countless adjacent service/driveways so use this many times, would love to have a one click for that with icon to pin to toolbar. Pretty please.

**Comment by simonpoole** [comment]
General comment: pls open separate issues for each separate issue when you have more than one. Not doing so makes tracking what has been done, following up, and in general managing issues very painful. 

1) depending on which icons you are using, the icon sets are more or less complete. If you find that an existing original JOSM icon is missing from the mapping here https://github.com/simonpoole/beautified-JOSM-preset/blob/master/josm_icons.txt please open a PR and add it. If you are using the icons from this project you have to create one and add it, see https://github.com/simonpoole/beautified-JOSM-preset/issues/4 for an (oldish) list of missing icons. In general icons are a continuos WIP. Note that if you are using the icons distributed with JOSM, you are limited to the icons distributed with JOSM, with other words: if we have a preset for which there is no icon in JOSM, you are not going to get an icon (that's why I personally prefer to use the version using the projects icons in JOSM).

2) We don't track issues opened on the JOSM issue tracker so no surprise here. Pls simply open an issue for this and it will get fixed.

3) JOSMs map rendering is out of scope here and doesn't use the presets in any case, but in general the "no exit" annotation is not a replacement for the traffic sign and vice versa. That is why we use a grey-scale icon see http://simonpoole.github.io/beautified-JOSM-preset/#Annotation, if you can find an appropriate icon in JOSM feel free to add it to the mapping see 1).

**Comment by sekerob** [comment]
Knew I was wasting my time, sorry to have wasted yours too, 

(I've found a No Exit icon and added it to my custom preset, the denotation I've added to the Tree Row custom preset).
