### ISSUE TITLE
add building tag to as value for multipolygon

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#79]
Multipolygon relations are not having building tag in drop-down. There are tags like building:use

Part of https://github.com/MarcusWolschon/osmeditor4android/issues/712 - fixing that would make creating multipolygon buildings a tiny bit less flustrating

**Comment by simonpoole** [comment]
Actually I don't think that is the correct fix.... a multipolygon is an OSM geometric element and you can simply apply the/a building preset to it once created (that could be made simpler though). What is annoying is that there is no generic relation preset that would match when you are creating the relation (because you haven't actually set the type tag yet).

**Comment by matkoniecz** [comment]
In my case I set type=multipolygon. I expected that typing "bu" will cause "building" tag to appear in the drop-down menu (like for a closed way).

**Comment by simonpoole** [comment]
https://github.com/simonpoole/beautified-JOSM-preset/commit/8b30e4b51e0b11bea3e4188167a951df884b5f35 adds a generic relation preset which simplifies the situation somewhat. 

That the building key was not present in the drop down was simply a bug (not determining the meta "element type" from the current tags when generating the autocomplete adapters), fixed in: https://github.com/MarcusWolschon/osmeditor4android/commit/5687dedaa0cfad32834e2ece712bae991f962089
