### ISSUE TITLE
show building:use and other building:* tags only for areas

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#81]
Some tags like leisure=park are restricted and not shown for unclosed ways

The same may be done for building:* tag family.

**Comment by simonpoole** [comment]
That is already the case.

**Comment by matkoniecz** [comment]
I just tested in in Vespucci beta with a simplest possible way (two boxes unlinked to anything) and I got building: family in suggestions after typing "bu"

Is it a Vespucci bug?

**Comment by simonpoole** [comment]
Not really a bug, but tags in chunks were added to the auto-complete lists per type on parsing, however at that time no applicable type is actually known (because it is a chunk) so there were added for all types.

Addressed in https://github.com/MarcusWolschon/osmeditor4android/commit/f817cfa0a5d2e852c83ddd10ec0fdd1bec5869b1
