### ISSUE TITLE
why not build link list automatically?

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/beautified-JOSM-preset#98]
based on https://github.com/simonpoole/beautified-JOSM-preset/commit/1249b73bef564637640081773e92b820838bf075 it seems that one is supposed to manually add existing wiki pages in each language.

Is there a good reason to not do automatically? Or is it because somebody would need to write such script?

https://github.com/openstreetmap/openstreetmap-website/blob/master/config/wiki_pages.yml and script generating it may be useful

**Comment by simonpoole** [comment]
There is no real reason to have language specific links to start with as long as they follow the same scheme (exceptions could still be explicitly listed), It's however something that the JOSM devs would need to consider as there is no simple way to go back to a JOSM compatible preset once that is changed.

**Comment by simonpoole** [comment]
See https://lists.openstreetmap.org/pipermail/josm-dev/2018-November/008171.html for a discussion, tl;dr version no chance at all of them budging at all, and even if it was just running Dirks script just before packaging the release instead of adding them to the editable version of the presets..

I might consider simply producing a JOSM compatible version with the added links using a similar mechanism as JOSM.

**Comment by simonpoole** [comment]
See https://github.com/MarcusWolschon/osmeditor4android/commit/b936dc2b776f1dabb31924d6b13e65d860019984 for how this is solved, "naturally" this means that we need to create two further versions of the presets for backwards compatibility.

**Comment by simonpoole** [comment]
New attribute is now in use https://github.com/simonpoole/beautified-JOSM-preset/commit/0d413237b0f7f4bb30b11a1bf521f8c480552c27
